# These are supported funding model platforms

github: [wulabing]
custom:
  - "https://app.proxy-cheap.com/r/Pbqf9l"
  - "https://iproyal.cn/?r=249487"
  - "https://bandwagonhost.com/aff.php?aff=63939"
  - "https://www.dmit.io/aff.php?aff=3957"
